# @license GPL-3.0-or-later
# Copyright (C) 2025 Caleb Gyamfi - Omnixys Technologies
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# For more information, visit <https://www.gnu.org/licenses/>.

name: 🧹 Cleanup Cancelled workflow after Release

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['Docker Build & Push – Omnixys']
    types: [completed]

permissions:
  actions: write
  contents: read

concurrency:
  group: cleanup-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cleanup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workflow:
          [
            'docker-build.yaml',
            'release.yaml',
            'changelog.yaml',
            'ci.yaml',
            'docs.yaml',
            'codeql-analysis.yaml',
            'tag-determine.yaml',
          ]
    steps:
      - name: Delete only failed, cancelled or skipped workflow runs
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          REPO: ${{ github.repository }}
          WORKFLOW_ID: ${{ matrix.workflow }}
          CURRENT_RUN_ID: ${{ github.run_id }}
        run: |
          echo "Fetching failed/cancelled workflow runs for $REPO ($WORKFLOW_ID)..."

          # Fetch list of failed/cancelled/skipped runs excluding current run
          # .conclusion == "failure" or 
          RUNS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPO/actions/workflows/$WORKFLOW_ID/runs?per_page=100" \
            | jq -r '.workflow_runs // [] | .[] 
              | select((.conclusion == "cancelled" or .conclusion == "skipped") 
                and (.id != '"$CURRENT_RUN_ID"')) 
              | .id')

          if [ -z "$RUNS" ]; then
            echo "✅ No failed or cancelled runs found for $WORKFLOW_ID."
            exit 0
          fi

          COUNT=$(echo "$RUNS" | wc -l | xargs)
          echo "Found $COUNT runs to delete."

          for RUN_ID in $RUNS; do
            echo "🗑️  Deleting run $RUN_ID ..."
            curl -s -X DELETE \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/$REPO/actions/runs/$RUN_ID"
            sleep 1
          done

          echo "✅ Cleanup complete."
