# @license GPL-3.0-or-later
# Copyright (C) 2025 Caleb Gyamfi - Omnixys Technologies
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# For more information, visit <https://www.gnu.org/licenses/>.
#
# Omnixys Workflow Suite – deploy.yml
# Purpose: Automated deployment for Omnixys services (Docker, Kubernetes, or Cloud platforms).
# Language: Node / TypeScript (pnpm)

name: Deployment – Omnixys

on:
  # workflow_run:
  #   workflows: ['Create GitHub Release – Omnixys', 'Docker Build & Push – Omnixys']
  #   types:
  #     - completed
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment (staging or production)'
        required: true
        default: 'staging'

permissions:
  contents: read
  deployments: write
  packages: read

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    name: Deploy Omnixys Service
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'staging' }}

    steps:
      - name: 🧾 Checkout repository
        uses: actions/checkout@v4

      - name: 🧩 Extract version
        id: version
        run: |
          if [ -f package.json ]; then
            VERSION=$(node -p "require('./package.json').version")
          else
            VERSION=${GITHUB_REF#refs/tags/}
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: 🔑 Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: 🐳 Pull built Docker image
        run: |
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}

      - name: ⚙️ Deploy using Docker Compose (staging)
        if: ${{ github.event.inputs.environment == 'staging' }}
        run: |
          echo "Deploying to staging environment..."
          docker compose -f docker-compose.staging.yml pull
          docker compose -f docker-compose.staging.yml up -d --remove-orphans

      - name: ☁️ Deploy to Kubernetes (production)
        if: ${{ github.event.inputs.environment == 'production' }}
        uses: azure/k8s-deploy@v5
        with:
          manifests: |
            k8s/deployment.yml
            k8s/service.yml
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}
          namespace: omnixys-prod
          strategy: rolling
          action: deploy
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

      - name: 🧠 Deployment summary
        run: |
          echo "✅ Deployment successful!"
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Version: ${{ steps.version.outputs.version }}"
          echo "Image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
