# @license GPL-3.0-or-later
# Copyright (C) 2025 Caleb Gyamfi - Omnixys Technologies
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# For more information, visit <https://www.gnu.org/licenses/>.
#
# Omnixys Workflow Suite – determine-version.yml
# Purpose: Determine next semantic version, update org variable, and push version bump.

name: Determine Next Version Tag – Omnixys

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  contents: write

jobs:
  determine:
    # Skip recursion when commit message comes from CI itself
    if: >
      !contains(github.event.head_commit.message, 'chore(version)') &&
      !contains(github.event.head_commit.message, 'docs(changelog)')
    runs-on: ubuntu-latest
    steps:
      - name: 🧾 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: ⚙️ Setup Node.js and pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm install --frozen-lockfile
          pnpm add -D semver jq

      - name: 🔎 Determine next semantic version (based on package.json)
        id: version
        run: |
          CURRENT=$(jq -r .version package.json)
          echo "Current version from package.json: $CURRENT"

          if git rev-parse "v$CURRENT" >/dev/null 2>&1; then
            echo "Tag v$CURRENT already exists — checking for new commits since then..."
            BASE_TAG="v$CURRENT"
          else
            echo "No existing tag for v$CURRENT found — keeping current version."
            echo "next_version=$CURRENT" >> $GITHUB_OUTPUT
            exit 0
          fi

          COMMITS=$(git log ${BASE_TAG}..HEAD --pretty=format:"%s" || echo "")
          echo "$COMMITS" > commits.txt

          NEXT="$CURRENT"
          if grep -q "BREAKING CHANGE" commits.txt; then
            NEXT=$(npx semver "$CURRENT" -i major)
             CHANGE_TYPE="major (breaking)"
          elif grep -q "feat" commits.txt; then
            NEXT=$(npx semver "$CURRENT" -i minor)
            CHANGE_TYPE="minor (feature)"
          elif grep -q "fix" commits.txt; then
            NEXT=$(npx semver "$CURRENT" -i patch)
            CHANGE_TYPE="patch (fix)"
          else
            echo "No semantic changes since $BASE_TAG — keeping version $CURRENT."
            echo "No semantic changes since $BASE_TAG — defaulting to patch bump."
            NEXT=$(npx semver "$CURRENT" -i patch)
            CHANGE_TYPE="patch (default)"
          fi

          echo "Detected change type: $CHANGE_TYPE"
          echo "Next version will be: $NEXT"
          echo "next_version=$NEXT" >> $GITHUB_OUTPUT

      - name: 🏷️ Update CURRENT_VERSION in repo variable
        run: |
          VERSION="v${{ steps.version.outputs.next_version }}"
          CURRENT=$(jq -r .version package.json)
          CLEAN_VERSION=${VERSION#v}
          echo "Current: $CURRENT, Next: $CLEAN_VERSION"

          if [ "$CURRENT" = "$CLEAN_VERSION" ]; then
            echo "package.json already at correct version ($CURRENT). Skipping update."
          else
            echo "Updating package.json to $CLEAN_VERSION"
            npm version --no-git-tag-version "$CLEAN_VERSION"
          fi

          OWNER=$(echo "${{ github.repository }}" | cut -d'/' -f1)
          REPO=$(echo "${{ github.repository }}" | cut -d'/' -f2)

          EXISTING=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${OWNER}/${REPO}/actions/variables/CURRENT_VERSION \
            | jq -r '.value')

          echo "Existing repo-level version: $EXISTING"
          echo "Updating CURRENT_VERSION to $VERSION"

          if [ "$EXISTING" = "null" ] || [ -z "$EXISTING" ]; then
            echo "Creating repo variable CURRENT_VERSION..."
            curl -X POST \
              -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/${OWNER}/${REPO}/actions/variables \
              -d "{\"name\": \"CURRENT_VERSION\", \"value\": \"${VERSION}\"}"
          elif [ "$EXISTING" != "$VERSION" ]; then
              curl -X PATCH \
                -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
                -H "Accept: application/vnd.github+json" \
                https://api.github.com/repos/${OWNER}/${REPO}/actions/variables/CURRENT_VERSION \
                -d "{\"value\": \"${VERSION}\"}"
            else
              echo "CURRENT_VERSION already up to date: $VERSION"
          fi

      - name: ⚙️ Remove semver and jq
        run: pnpm remove -D semver jq

      - name: 💾 Commit and push new version if changed
        run: |
          VERSION="${{ steps.version.outputs.next_version }}"
          if git diff --quiet package.json; then
            echo "No version change to commit."
            exit 0
          fi
          git config user.name "omnixys-bot"
          git config user.email "bot@omnixys.com"
          git add package.json
          git commit -m "chore(version): bump to v${VERSION}" || echo "No changes"
          git push origin main
